/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ChoreQueueRouteImport } from './routes/chore-queue'
import { Route as IndexRouteImport } from './routes/index'

const ChoreQueueRoute = ChoreQueueRouteImport.update({
  id: '/chore-queue',
  path: '/chore-queue',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chore-queue': typeof ChoreQueueRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chore-queue': typeof ChoreQueueRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chore-queue': typeof ChoreQueueRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/chore-queue'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/chore-queue'
  id: '__root__' | '/' | '/chore-queue'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChoreQueueRoute: typeof ChoreQueueRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/chore-queue': {
      id: '/chore-queue'
      path: '/chore-queue'
      fullPath: '/chore-queue'
      preLoaderRoute: typeof ChoreQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChoreQueueRoute: ChoreQueueRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
