/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TodayRouteImport } from './routes/today'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChoresManageRouteImport } from './routes/chores/manage'
import { Route as ChoresImportRouteImport } from './routes/chores/import'

const TodayRoute = TodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChoresManageRoute = ChoresManageRouteImport.update({
  id: '/chores/manage',
  path: '/chores/manage',
  getParentRoute: () => rootRouteImport,
} as any)
const ChoresImportRoute = ChoresImportRouteImport.update({
  id: '/chores/import',
  path: '/chores/import',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/today': typeof TodayRoute
  '/chores/import': typeof ChoresImportRoute
  '/chores/manage': typeof ChoresManageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/today': typeof TodayRoute
  '/chores/import': typeof ChoresImportRoute
  '/chores/manage': typeof ChoresManageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/today': typeof TodayRoute
  '/chores/import': typeof ChoresImportRoute
  '/chores/manage': typeof ChoresManageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/today' | '/chores/import' | '/chores/manage'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/today' | '/chores/import' | '/chores/manage'
  id: '__root__' | '/' | '/today' | '/chores/import' | '/chores/manage'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TodayRoute: typeof TodayRoute
  ChoresImportRoute: typeof ChoresImportRoute
  ChoresManageRoute: typeof ChoresManageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/today': {
      id: '/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof TodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chores/manage': {
      id: '/chores/manage'
      path: '/chores/manage'
      fullPath: '/chores/manage'
      preLoaderRoute: typeof ChoresManageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chores/import': {
      id: '/chores/import'
      path: '/chores/import'
      fullPath: '/chores/import'
      preLoaderRoute: typeof ChoresImportRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TodayRoute: TodayRoute,
  ChoresImportRoute: ChoresImportRoute,
  ChoresManageRoute: ChoresManageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
