// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import "do-your-dailies/server/internal/utctime"

// Chore defines model for Chore.
type Chore struct {
	CadenceInDays int          `json:"cadenceInDays"`
	CreatedAt     utctime.Time `json:"createdAt"`
	Id            uint64       `json:"id"`
	Name          string       `json:"name"`
	UpdatedAt     utctime.Time `json:"updatedAt"`
}

// ChoreCompletion defines model for ChoreCompletion.
type ChoreCompletion struct {
	ChoreId   uint64       `json:"choreId"`
	CreatedAt utctime.Time `json:"createdAt"`
	Id        uint64       `json:"id"`
	UpdatedAt utctime.Time `json:"updatedAt"`
}

// CreateChoreCompletionRequest defines model for CreateChoreCompletionRequest.
type CreateChoreCompletionRequest struct {
	ChoreId uint64 `json:"choreId"`
}

// CreateChoreRequest defines model for CreateChoreRequest.
type CreateChoreRequest struct {
	CadenceInDays int    `json:"cadenceInDays"`
	Name          string `json:"name"`
}

// UpdateChoreRequest defines model for UpdateChoreRequest.
type UpdateChoreRequest struct {
	CadenceInDays *int    `json:"cadenceInDays,omitempty"`
	Name          *string `json:"name,omitempty"`
}

// ListChoreQueueParams defines parameters for ListChoreQueue.
type ListChoreQueueParams struct {
	DayOffset *int `form:"dayOffset,omitempty" json:"dayOffset,omitempty"`
	MaxChores *int `form:"maxChores,omitempty" json:"maxChores,omitempty"`
}

// CreateChoreCompletionJSONRequestBody defines body for CreateChoreCompletion for application/json ContentType.
type CreateChoreCompletionJSONRequestBody = CreateChoreCompletionRequest

// CreateChoreJSONRequestBody defines body for CreateChore for application/json ContentType.
type CreateChoreJSONRequestBody = CreateChoreRequest

// UpdateChoreJSONRequestBody defines body for UpdateChore for application/json ContentType.
type UpdateChoreJSONRequestBody = UpdateChoreRequest
