// Package contracts provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package contracts

import "do-your-dailies/server/internal/utctime"

// Chore defines model for Chore.
type Chore struct {
	CadenceInDays int          `json:"cadenceInDays"`
	CreatedAt     utctime.Time `json:"createdAt"`
	Id            uint64       `json:"id"`
	Name          string       `json:"name"`
	UpdatedAt     utctime.Time `json:"updatedAt"`
}

// ChoreCompletion defines model for ChoreCompletion.
type ChoreCompletion struct {
	ChoreId   uint64       `json:"choreId"`
	CreatedAt utctime.Time `json:"createdAt"`
	Id        uint64       `json:"id"`
	UpdatedAt utctime.Time `json:"updatedAt"`
}

// ChoreInQueue defines model for ChoreInQueue.
type ChoreInQueue struct {
	CadenceInDays      int           `json:"cadenceInDays"`
	ChoreId            uint64        `json:"choreId"`
	ChoreName          string        `json:"choreName"`
	LastCompletedAt    *utctime.Time `json:"lastCompletedAt,omitempty"`
	LatestCompletionId *uint64       `json:"latestCompletionId,omitempty"`
	Priority           float32       `json:"priority"`
}

// CreateChoreCompletionRequest defines model for CreateChoreCompletionRequest.
type CreateChoreCompletionRequest struct {
	ChoreId uint64 `json:"choreId"`
}

// CreateChoreRequest defines model for CreateChoreRequest.
type CreateChoreRequest struct {
	CadenceInDays int    `json:"cadenceInDays"`
	Name          string `json:"name"`
}

// UpdateChoreRequest defines model for UpdateChoreRequest.
type UpdateChoreRequest struct {
	CadenceInDays *int    `json:"cadenceInDays,omitempty"`
	Name          *string `json:"name,omitempty"`
}

// ListChoreCompletionsParams defines parameters for ListChoreCompletions.
type ListChoreCompletionsParams struct {
	Start utctime.Time `form:"start" json:"start"`
	End   utctime.Time `form:"end" json:"end"`
}

// ListChoreQueueParams defines parameters for ListChoreQueue.
type ListChoreQueueParams struct {
	MaxChores *int `form:"maxChores,omitempty" json:"maxChores,omitempty"`
}

// CreateChoreCompletionJSONRequestBody defines body for CreateChoreCompletion for application/json ContentType.
type CreateChoreCompletionJSONRequestBody = CreateChoreCompletionRequest

// CreateChoreJSONRequestBody defines body for CreateChore for application/json ContentType.
type CreateChoreJSONRequestBody = CreateChoreRequest

// UpdateChoreJSONRequestBody defines body for UpdateChore for application/json ContentType.
type UpdateChoreJSONRequestBody = UpdateChoreRequest
