// Package contracts provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package contracts

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// BulkCreateChoresRequest defines model for BulkCreateChoresRequest.
type BulkCreateChoresRequest struct {
	Chores []CreateChoreRequest `json:"chores"`
}

// BulkCreateChoresRowError defines model for BulkCreateChoresRowError.
type BulkCreateChoresRowError struct {
	Index   int    `json:"index"`
	Message string `json:"message"`
}

// BulkCreateChoresValidationError defines model for BulkCreateChoresValidationError.
type BulkCreateChoresValidationError struct {
	Errors []BulkCreateChoresRowError `json:"errors"`
}

// Chore defines model for Chore.
type Chore struct {
	CadenceInDays int       `json:"cadenceInDays"`
	CreatedAt     time.Time `json:"createdAt"`
	Id            uint64    `json:"id"`
	Name          string    `json:"name"`
	UpdatedAt     time.Time `json:"updatedAt"`
}

// ChoreCompletion defines model for ChoreCompletion.
type ChoreCompletion struct {
	ChoreId   uint64    `json:"choreId"`
	CreatedAt time.Time `json:"createdAt"`
	Id        uint64    `json:"id"`
	UpdatedAt time.Time `json:"updatedAt"`
}

// ChoreInQueue defines model for ChoreInQueue.
type ChoreInQueue struct {
	CadenceInDays      int        `json:"cadenceInDays"`
	ChoreId            uint64     `json:"choreId"`
	ChoreName          string     `json:"choreName"`
	LastCompletedAt    *time.Time `json:"lastCompletedAt,omitempty"`
	LatestCompletionId *uint64    `json:"latestCompletionId,omitempty"`
	Priority           float32    `json:"priority"`
}

// ChoreInsights defines model for ChoreInsights.
type ChoreInsights struct {
	ChoreProjections                                []ChoreProjection `json:"choreProjections"`
	MinCapacityToKeepUtilizationRatioGreaterThanOne float64           `json:"minCapacityToKeepUtilizationRatioGreaterThanOne"`
	UserDesiredCapacity                             int               `json:"userDesiredCapacity"`
	UtilizationRatio                                float64           `json:"utilizationRatio"`
}

// ChoreProjection defines model for ChoreProjection.
type ChoreProjection struct {
	Chore            Chore   `json:"chore"`
	ProjectedCadence float64 `json:"projectedCadence"`
}

// CreateChoreCompletionRequest defines model for CreateChoreCompletionRequest.
type CreateChoreCompletionRequest struct {
	ChoreId uint64 `json:"choreId"`
}

// CreateChoreRequest defines model for CreateChoreRequest.
type CreateChoreRequest struct {
	CadenceInDays int    `json:"cadenceInDays"`
	Name          string `json:"name"`
}

// UpdateChoreRequest defines model for UpdateChoreRequest.
type UpdateChoreRequest struct {
	CadenceInDays *int    `json:"cadenceInDays,omitempty"`
	Name          *string `json:"name,omitempty"`
}

// ListChoreCompletionsParams defines parameters for ListChoreCompletions.
type ListChoreCompletionsParams struct {
	Start time.Time `form:"start" json:"start"`
	End   time.Time `form:"end" json:"end"`
}

// CreateChoreCompletionJSONRequestBody defines body for CreateChoreCompletion for application/json ContentType.
type CreateChoreCompletionJSONRequestBody = CreateChoreCompletionRequest

// CreateChoreJSONRequestBody defines body for CreateChore for application/json ContentType.
type CreateChoreJSONRequestBody = CreateChoreRequest

// BulkCreateChoresJSONRequestBody defines body for BulkCreateChores for application/json ContentType.
type BulkCreateChoresJSONRequestBody = BulkCreateChoresRequest

// UpdateChoreJSONRequestBody defines body for UpdateChore for application/json ContentType.
type UpdateChoreJSONRequestBody = UpdateChoreRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /api/chore-completions)
	ListChoreCompletions(w http.ResponseWriter, r *http.Request, params ListChoreCompletionsParams)

	// (POST /api/chore-completions)
	CreateChoreCompletion(w http.ResponseWriter, r *http.Request)

	// (GET /api/chore-insights)
	GetChoreInsights(w http.ResponseWriter, r *http.Request)

	// (GET /api/chore-queue)
	ListChoreQueue(w http.ResponseWriter, r *http.Request)

	// (GET /api/chores)
	ListChores(w http.ResponseWriter, r *http.Request)

	// (POST /api/chores)
	CreateChore(w http.ResponseWriter, r *http.Request)

	// (POST /api/chores/bulk)
	BulkCreateChores(w http.ResponseWriter, r *http.Request)

	// (DELETE /api/chores/{id})
	DeleteChore(w http.ResponseWriter, r *http.Request, id uint64)

	// (GET /api/chores/{id})
	GetChore(w http.ResponseWriter, r *http.Request, id uint64)

	// (PUT /api/chores/{id})
	UpdateChore(w http.ResponseWriter, r *http.Request, id uint64)

	// (GET /health)
	HealthCheck(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// (GET /api/chore-completions)
func (_ Unimplemented) ListChoreCompletions(w http.ResponseWriter, r *http.Request, params ListChoreCompletionsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /api/chore-completions)
func (_ Unimplemented) CreateChoreCompletion(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/chore-insights)
func (_ Unimplemented) GetChoreInsights(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/chore-queue)
func (_ Unimplemented) ListChoreQueue(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/chores)
func (_ Unimplemented) ListChores(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /api/chores)
func (_ Unimplemented) CreateChore(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /api/chores/bulk)
func (_ Unimplemented) BulkCreateChores(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (DELETE /api/chores/{id})
func (_ Unimplemented) DeleteChore(w http.ResponseWriter, r *http.Request, id uint64) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/chores/{id})
func (_ Unimplemented) GetChore(w http.ResponseWriter, r *http.Request, id uint64) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PUT /api/chores/{id})
func (_ Unimplemented) UpdateChore(w http.ResponseWriter, r *http.Request, id uint64) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /health)
func (_ Unimplemented) HealthCheck(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListChoreCompletions operation middleware
func (siw *ServerInterfaceWrapper) ListChoreCompletions(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListChoreCompletionsParams

	// ------------- Required query parameter "start" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "start", r.URL.Query(), &params.Start, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "start"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "start", Err: err})
		}
		return
	}

	// ------------- Required query parameter "end" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "end", r.URL.Query(), &params.End, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "end"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "end", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListChoreCompletions(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateChoreCompletion operation middleware
func (siw *ServerInterfaceWrapper) CreateChoreCompletion(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateChoreCompletion(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetChoreInsights operation middleware
func (siw *ServerInterfaceWrapper) GetChoreInsights(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetChoreInsights(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListChoreQueue operation middleware
func (siw *ServerInterfaceWrapper) ListChoreQueue(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListChoreQueue(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListChores operation middleware
func (siw *ServerInterfaceWrapper) ListChores(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListChores(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateChore operation middleware
func (siw *ServerInterfaceWrapper) CreateChore(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateChore(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// BulkCreateChores operation middleware
func (siw *ServerInterfaceWrapper) BulkCreateChores(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.BulkCreateChores(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteChore operation middleware
func (siw *ServerInterfaceWrapper) DeleteChore(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id uint64

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "uint64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteChore(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetChore operation middleware
func (siw *ServerInterfaceWrapper) GetChore(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id uint64

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "uint64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetChore(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateChore operation middleware
func (siw *ServerInterfaceWrapper) UpdateChore(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id uint64

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "uint64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateChore(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// HealthCheck operation middleware
func (siw *ServerInterfaceWrapper) HealthCheck(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.HealthCheck(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/chore-completions", wrapper.ListChoreCompletions)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/chore-completions", wrapper.CreateChoreCompletion)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/chore-insights", wrapper.GetChoreInsights)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/chore-queue", wrapper.ListChoreQueue)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/chores", wrapper.ListChores)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/chores", wrapper.CreateChore)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/chores/bulk", wrapper.BulkCreateChores)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/chores/{id}", wrapper.DeleteChore)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/chores/{id}", wrapper.GetChore)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/api/chores/{id}", wrapper.UpdateChore)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/health", wrapper.HealthCheck)
	})

	return r
}

type ListChoreCompletionsRequestObject struct {
	Params ListChoreCompletionsParams
}

type ListChoreCompletionsResponseObject interface {
	VisitListChoreCompletionsResponse(w http.ResponseWriter) error
}

type ListChoreCompletions200JSONResponse []ChoreCompletion

func (response ListChoreCompletions200JSONResponse) VisitListChoreCompletionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListChoreCompletions400Response struct {
}

func (response ListChoreCompletions400Response) VisitListChoreCompletionsResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type CreateChoreCompletionRequestObject struct {
	Body *CreateChoreCompletionJSONRequestBody
}

type CreateChoreCompletionResponseObject interface {
	VisitCreateChoreCompletionResponse(w http.ResponseWriter) error
}

type CreateChoreCompletion201JSONResponse ChoreCompletion

func (response CreateChoreCompletion201JSONResponse) VisitCreateChoreCompletionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateChoreCompletion404Response struct {
}

func (response CreateChoreCompletion404Response) VisitCreateChoreCompletionResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type CreateChoreCompletion422Response struct {
}

func (response CreateChoreCompletion422Response) VisitCreateChoreCompletionResponse(w http.ResponseWriter) error {
	w.WriteHeader(422)
	return nil
}

type GetChoreInsightsRequestObject struct {
}

type GetChoreInsightsResponseObject interface {
	VisitGetChoreInsightsResponse(w http.ResponseWriter) error
}

type GetChoreInsights200JSONResponse ChoreInsights

func (response GetChoreInsights200JSONResponse) VisitGetChoreInsightsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListChoreQueueRequestObject struct {
}

type ListChoreQueueResponseObject interface {
	VisitListChoreQueueResponse(w http.ResponseWriter) error
}

type ListChoreQueue200JSONResponse []ChoreInQueue

func (response ListChoreQueue200JSONResponse) VisitListChoreQueueResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListChoresRequestObject struct {
}

type ListChoresResponseObject interface {
	VisitListChoresResponse(w http.ResponseWriter) error
}

type ListChores200JSONResponse []Chore

func (response ListChores200JSONResponse) VisitListChoresResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type CreateChoreRequestObject struct {
	Body *CreateChoreJSONRequestBody
}

type CreateChoreResponseObject interface {
	VisitCreateChoreResponse(w http.ResponseWriter) error
}

type CreateChore201JSONResponse Chore

func (response CreateChore201JSONResponse) VisitCreateChoreResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateChore422Response struct {
}

func (response CreateChore422Response) VisitCreateChoreResponse(w http.ResponseWriter) error {
	w.WriteHeader(422)
	return nil
}

type BulkCreateChoresRequestObject struct {
	Body *BulkCreateChoresJSONRequestBody
}

type BulkCreateChoresResponseObject interface {
	VisitBulkCreateChoresResponse(w http.ResponseWriter) error
}

type BulkCreateChores201JSONResponse []Chore

func (response BulkCreateChores201JSONResponse) VisitBulkCreateChoresResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type BulkCreateChores422JSONResponse BulkCreateChoresValidationError

func (response BulkCreateChores422JSONResponse) VisitBulkCreateChoresResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteChoreRequestObject struct {
	Id uint64 `json:"id"`
}

type DeleteChoreResponseObject interface {
	VisitDeleteChoreResponse(w http.ResponseWriter) error
}

type DeleteChore204Response struct {
}

func (response DeleteChore204Response) VisitDeleteChoreResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteChore404Response struct {
}

func (response DeleteChore404Response) VisitDeleteChoreResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type GetChoreRequestObject struct {
	Id uint64 `json:"id"`
}

type GetChoreResponseObject interface {
	VisitGetChoreResponse(w http.ResponseWriter) error
}

type GetChore200JSONResponse Chore

func (response GetChore200JSONResponse) VisitGetChoreResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetChore404Response struct {
}

func (response GetChore404Response) VisitGetChoreResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type UpdateChoreRequestObject struct {
	Id   uint64 `json:"id"`
	Body *UpdateChoreJSONRequestBody
}

type UpdateChoreResponseObject interface {
	VisitUpdateChoreResponse(w http.ResponseWriter) error
}

type UpdateChore200JSONResponse Chore

func (response UpdateChore200JSONResponse) VisitUpdateChoreResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateChore404Response struct {
}

func (response UpdateChore404Response) VisitUpdateChoreResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type UpdateChore422Response struct {
}

func (response UpdateChore422Response) VisitUpdateChoreResponse(w http.ResponseWriter) error {
	w.WriteHeader(422)
	return nil
}

type HealthCheckRequestObject struct {
}

type HealthCheckResponseObject interface {
	VisitHealthCheckResponse(w http.ResponseWriter) error
}

type HealthCheck200TextResponse string

func (response HealthCheck200TextResponse) VisitHealthCheckResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(200)

	_, err := w.Write([]byte(response))
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (GET /api/chore-completions)
	ListChoreCompletions(ctx context.Context, request ListChoreCompletionsRequestObject) (ListChoreCompletionsResponseObject, error)

	// (POST /api/chore-completions)
	CreateChoreCompletion(ctx context.Context, request CreateChoreCompletionRequestObject) (CreateChoreCompletionResponseObject, error)

	// (GET /api/chore-insights)
	GetChoreInsights(ctx context.Context, request GetChoreInsightsRequestObject) (GetChoreInsightsResponseObject, error)

	// (GET /api/chore-queue)
	ListChoreQueue(ctx context.Context, request ListChoreQueueRequestObject) (ListChoreQueueResponseObject, error)

	// (GET /api/chores)
	ListChores(ctx context.Context, request ListChoresRequestObject) (ListChoresResponseObject, error)

	// (POST /api/chores)
	CreateChore(ctx context.Context, request CreateChoreRequestObject) (CreateChoreResponseObject, error)

	// (POST /api/chores/bulk)
	BulkCreateChores(ctx context.Context, request BulkCreateChoresRequestObject) (BulkCreateChoresResponseObject, error)

	// (DELETE /api/chores/{id})
	DeleteChore(ctx context.Context, request DeleteChoreRequestObject) (DeleteChoreResponseObject, error)

	// (GET /api/chores/{id})
	GetChore(ctx context.Context, request GetChoreRequestObject) (GetChoreResponseObject, error)

	// (PUT /api/chores/{id})
	UpdateChore(ctx context.Context, request UpdateChoreRequestObject) (UpdateChoreResponseObject, error)

	// (GET /health)
	HealthCheck(ctx context.Context, request HealthCheckRequestObject) (HealthCheckResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListChoreCompletions operation middleware
func (sh *strictHandler) ListChoreCompletions(w http.ResponseWriter, r *http.Request, params ListChoreCompletionsParams) {
	var request ListChoreCompletionsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListChoreCompletions(ctx, request.(ListChoreCompletionsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListChoreCompletions")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListChoreCompletionsResponseObject); ok {
		if err := validResponse.VisitListChoreCompletionsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateChoreCompletion operation middleware
func (sh *strictHandler) CreateChoreCompletion(w http.ResponseWriter, r *http.Request) {
	var request CreateChoreCompletionRequestObject

	var body CreateChoreCompletionJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateChoreCompletion(ctx, request.(CreateChoreCompletionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateChoreCompletion")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateChoreCompletionResponseObject); ok {
		if err := validResponse.VisitCreateChoreCompletionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetChoreInsights operation middleware
func (sh *strictHandler) GetChoreInsights(w http.ResponseWriter, r *http.Request) {
	var request GetChoreInsightsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetChoreInsights(ctx, request.(GetChoreInsightsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetChoreInsights")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetChoreInsightsResponseObject); ok {
		if err := validResponse.VisitGetChoreInsightsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListChoreQueue operation middleware
func (sh *strictHandler) ListChoreQueue(w http.ResponseWriter, r *http.Request) {
	var request ListChoreQueueRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListChoreQueue(ctx, request.(ListChoreQueueRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListChoreQueue")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListChoreQueueResponseObject); ok {
		if err := validResponse.VisitListChoreQueueResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListChores operation middleware
func (sh *strictHandler) ListChores(w http.ResponseWriter, r *http.Request) {
	var request ListChoresRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListChores(ctx, request.(ListChoresRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListChores")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListChoresResponseObject); ok {
		if err := validResponse.VisitListChoresResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateChore operation middleware
func (sh *strictHandler) CreateChore(w http.ResponseWriter, r *http.Request) {
	var request CreateChoreRequestObject

	var body CreateChoreJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateChore(ctx, request.(CreateChoreRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateChore")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateChoreResponseObject); ok {
		if err := validResponse.VisitCreateChoreResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// BulkCreateChores operation middleware
func (sh *strictHandler) BulkCreateChores(w http.ResponseWriter, r *http.Request) {
	var request BulkCreateChoresRequestObject

	var body BulkCreateChoresJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.BulkCreateChores(ctx, request.(BulkCreateChoresRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "BulkCreateChores")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(BulkCreateChoresResponseObject); ok {
		if err := validResponse.VisitBulkCreateChoresResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteChore operation middleware
func (sh *strictHandler) DeleteChore(w http.ResponseWriter, r *http.Request, id uint64) {
	var request DeleteChoreRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteChore(ctx, request.(DeleteChoreRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteChore")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteChoreResponseObject); ok {
		if err := validResponse.VisitDeleteChoreResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetChore operation middleware
func (sh *strictHandler) GetChore(w http.ResponseWriter, r *http.Request, id uint64) {
	var request GetChoreRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetChore(ctx, request.(GetChoreRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetChore")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetChoreResponseObject); ok {
		if err := validResponse.VisitGetChoreResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateChore operation middleware
func (sh *strictHandler) UpdateChore(w http.ResponseWriter, r *http.Request, id uint64) {
	var request UpdateChoreRequestObject

	request.Id = id

	var body UpdateChoreJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateChore(ctx, request.(UpdateChoreRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateChore")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateChoreResponseObject); ok {
		if err := validResponse.VisitUpdateChoreResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// HealthCheck operation middleware
func (sh *strictHandler) HealthCheck(w http.ResponseWriter, r *http.Request) {
	var request HealthCheckRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.HealthCheck(ctx, request.(HealthCheckRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "HealthCheck")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(HealthCheckResponseObject); ok {
		if err := validResponse.VisitHealthCheckResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
