// Package contracts provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package contracts

import (
	"time"
)

// Chore defines model for Chore.
type Chore struct {
	CadenceInDays int       `json:"cadenceInDays"`
	CreatedAt     time.Time `json:"createdAt"`
	Id            uint64    `json:"id"`
	Name          string    `json:"name"`
	UpdatedAt     time.Time `json:"updatedAt"`
}

// ChoreCompletion defines model for ChoreCompletion.
type ChoreCompletion struct {
	ChoreId   uint64    `json:"choreId"`
	CreatedAt time.Time `json:"createdAt"`
	Id        uint64    `json:"id"`
	UpdatedAt time.Time `json:"updatedAt"`
}

// CreateChoreCompletionRequest defines model for CreateChoreCompletionRequest.
type CreateChoreCompletionRequest struct {
	ChoreId uint64 `json:"choreId"`
}

// CreateChoreRequest defines model for CreateChoreRequest.
type CreateChoreRequest struct {
	CadenceInDays int    `json:"cadenceInDays"`
	Name          string `json:"name"`
}

// UpdateChoreRequest defines model for UpdateChoreRequest.
type UpdateChoreRequest struct {
	CadenceInDays *int    `json:"cadenceInDays,omitempty"`
	Name          *string `json:"name,omitempty"`
}

// CreateChoreCompletionJSONRequestBody defines body for CreateChoreCompletion for application/json ContentType.
type CreateChoreCompletionJSONRequestBody = CreateChoreCompletionRequest

// CreateChoreJSONRequestBody defines body for CreateChore for application/json ContentType.
type CreateChoreJSONRequestBody = CreateChoreRequest

// UpdateChoreJSONRequestBody defines body for UpdateChore for application/json ContentType.
type UpdateChoreJSONRequestBody = UpdateChoreRequest
